### ISSUE TITLE
small typo in rspatial tutorial

### ISSUE THREAD

**Issue by carmerlun** [rspatial/rspatial-terra-web#10]
In https://rspatial.org/terra/spatial/7-vectmanip.html#records
Where it says: "See ?select for interactively"

Might be '?sel', instead. (although '?sel' doens't correctly show any help page). Anyway, sel(df) works fine selecting geometries in a plot.

My R version 4.0.4, terra_1.7-3

PS. Sorry I forgot to ask if it is useful or appropiate to inform about typos here as issues.
PPS. Here is another dummy typo: "For this example, we first we get the name of an example file [...]" at https://rspatial.org/terra/spatial/8-rastermanip.html#creating-spatraster-objects.

**Comment by rhijmans** [comment]
Thanks very much for reporting this. `?sel` works for me (after loading terra). I moved your comment here as this is the repo for the terra materials of the rspatial site.
