### ISSUE TITLE
Raster vs. raster vs. SpatRaster

### ISSUE THREAD

**Issue by christophfriedrich** [rspatial/rspatial-terra-web#7]
Reading through https://rspatial.org/terra/spatial/8-rastermanip.html I not only came across the `SpatRaster` class, but apparently also `raster` and `Raster`. Sometimes this confused me. Especially I didn't know if `raster`and `Raster` are the same or not.

Examples:

> Many generic functions that allow for simple and elegant raster algebra have been implemented for `Raster` objects [...] In these functions you can mix `raster` objects with numbers, as long as the first argument is a `raster` object. [...] Create an empty `SpatRaster` and assign values to cells.

> The origin of a `Raster` object is the point closest to (0, 0) that you could get if you moved from a corner of a `SpatRaster` toward that point in steps of the x and y resolution.

> The crop function lets you take a geographic subset of a larger `raster` object. You can crop a `SpatRaster` by providing an extent object or another spatial object from which an extent can be extracted (objects from classes deriving from `Raster` and from Spatial in the sp package).

Could you clarify the connection between these somewhere? It may be obvious for you developers, but it isn't for newbies.

Sorry if this already exists, but I didn't come across it in https://rspatial.org/terra/spatial/2-spatialdata.html nor https://rspatial.org/terra/spatial/4-rasterdata.html.

**Comment by rhijmans** [comment]
Thanks for pointing this out. 
A "raster" is a generic term. A "SpatRaster" a class from terra. "Raster" "Raster*" etc are holdovers from the version of this manual for the "raster" package. They should not be there, but where missed when adapting the text. I think I have now removed these (or most of these).
